# Generated by Django 4.2.8 on 2023-12-16 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_ru', models.CharField(max_length=255, unique=True, verbose_name='Название на русском')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название на английском')),
                ('category_code', models.SmallIntegerField(blank=True, default=10, null=True)),
            ],
            options={
                'ordering': ('name_ru', 'category_code'),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.IntegerField(verbose_name='Код поставщика')),
                ('internal_code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Код в приложении')),
                ('package_length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина упаковки')),
                ('package_width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ширина упаковки')),
                ('package_height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Высота упаковки')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание на русском')),
                ('description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание на английском')),
                ('amount', models.IntegerField(verbose_name='Кол-во единиц на складе')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Текущий ассортимент')),
                ('additional', models.ManyToManyField(blank=True, related_name='additional_from', to='storage_app.item', verbose_name='Дополнительная информация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_app.category', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
